#version 430 core

layout (local_size_x = 16, local_size_y = 16) in;
layout (rgba8, binding = 0) uniform image2D imgOutput;

void main() {
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(imgOutput);

    // Prevent out-of-bounds writes
    if (coord.x >= size.x || coord.y >= size.y)
    return;

    // Normalize coordinates to 0.0 -> 1.0
    vec2 uv = vec2(coord) / vec2(size);

    vec4 color = vec4(uv.x, uv.y, 0.5, 1.0);

    imageStore(imgOutput, coord, color);
}