#version 430 core

layout (local_size_x = 16, local_size_y = 16) in;

layout (rgba8, binding = 0) uniform image2D imgInput;
layout (rgba8, binding = 1) writeonly uniform image2D imgOutput;

layout (std430, binding = 0) readonly buffer FFTBuffer { float fftData[];};

uniform int rawFFTSize;

uniform int dataWidth;
uniform int waterfallHeight;

uniform float waterfallMin;
uniform float waterfallMax;

uniform float wholeBandwidth;
uniform float viewBandwidth;
uniform float viewOffset;

vec4 colorMap(float v)
{
    return vec4(v, v, v, 1.0);
}

void main()
{
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);

    if (coord.x >= dataWidth || coord.y >= waterfallHeight)
    return;

    if (coord.y > 0)
    {
        vec4 prev =
        imageLoad(
            imgOutput,
            ivec2(coord.x, coord.y - 1)
        );

        imageStore(imgOutput, coord, prev);

        return;
    }

    int x = coord.x;

    float offsetRatio = viewOffset / (wholeBandwidth * 0.5);

    int drawDataSize = int((viewBandwidth / wholeBandwidth) * rawFFTSize);

    int drawDataStart = int((float(rawFFTSize) * 0.5) * (offsetRatio + 1.0)) - (drawDataSize / 2);

    drawDataStart = max(drawDataStart, 0);

    float factor = float(drawDataSize) / float(dataWidth);

    float id = float(drawDataStart) + float(x) * factor;

    int sId = int(id);

    int sampleWidth = int(ceil(factor));

    sampleWidth = min(sampleWidth, rawFFTSize - sId);

    float maxVal = -3.402823e38;

    for (int i = 0; i < sampleWidth; i++)
    {
        float v = fftData[sId + i];
        maxVal = max(maxVal, v);
    }

    float pixel = clamp(maxVal, waterfallMin, waterfallMax);

    pixel = (pixel - waterfallMin) / (waterfallMax - waterfallMin);

    imageStore(
        imgOutput,
        coord,
        colorMap(pixel)
    );
}